// AUTO-GENERATED by scripts/build-image-manifest.ts — do not edit by hand.
// Maps each CMS homepage image URL to its responsive widths per format
// (AVIF first, then WebP, then the JPEG fallback every browser understands)
// plus a tiny base64 blur-up placeholder.
export type ImageFormat = "avif" | "webp" | "jpg";
export interface ImageWidth { width: number; url: string }
export interface ImageSource { format: ImageFormat; widths: ImageWidth[] }
export interface ImageEntry { placeholder?: string; sources: ImageSource[] }

export const IMAGE_VARIANTS: Record<string, ImageEntry> = {
  "/media/hero.jpg": {
    placeholder: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFAv/EACIQAAIABQQDAQAAAAAAAAAAAAECAAMEESEFEkFRIjFC8P/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwB2ZrNPTqqKrTSBlgeIVqdbmuSKZCAb2Nrn9mJNKBMO1wGBB9iBpaZ8YjVyNPqNdM2sXqASPnF89QRPcbbBSwFjyezBCH//2Q==",
    sources: [
      { format: "avif", widths: [{ width: 480, url: "/media/hero-480w.avif" }, { width: 768, url: "/media/hero-768w.avif" }, { width: 1200, url: "/media/hero-1200w.avif" }, { width: 1600, url: "/media/hero-1600w.avif" }, { width: 1920, url: "/media/hero-1920w.avif" }] },
      { format: "webp", widths: [{ width: 480, url: "/media/hero-480w.webp" }, { width: 768, url: "/media/hero-768w.webp" }, { width: 1200, url: "/media/hero-1200w.webp" }, { width: 1600, url: "/media/hero-1600w.webp" }, { width: 1920, url: "/media/hero-1920w.webp" }] },
      { format: "jpg", widths: [{ width: 480, url: "/media/hero-480w.jpg" }, { width: 768, url: "/media/hero-768w.jpg" }, { width: 1200, url: "/media/hero-1200w.jpg" }, { width: 1600, url: "/media/hero-1600w.jpg" }, { width: 1920, url: "/media/hero.jpg" }] },
    ],
  },
  "/media/p1.jpg": {
    placeholder: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAMCBAUB/8QAJxAAAQQBAgMJAAAAAAAAAAAAAQACAwQREiEFQXIUMlFTYXGSsdH/xAAXAQADAQAAAAAAAAAAAAAAAAAAAQID/8QAGREBAQEAAwAAAAAAAAAAAAAAABEBITFB/9oADAMBAAIRAxEAPwCvBUr0roF4sYAA4B24Izy8dlpW+NV3RS14oCY3NxqH4sCxLrjgexhcRHgEtyRg+iUZhE3JZknks7udLnumPfDq2BPVt9IVY2Yye4B7BCdHDZgY1jNDQA3GMBRdSrO3czJ6iuMUuauJL7BV8s/IoTEIJ//Z",
    sources: [
      { format: "avif", widths: [{ width: 480, url: "/media/p1-480w.avif" }, { width: 768, url: "/media/p1-768w.avif" }, { width: 1200, url: "/media/p1-1200w.avif" }] },
      { format: "webp", widths: [{ width: 480, url: "/media/p1-480w.webp" }, { width: 768, url: "/media/p1-768w.webp" }, { width: 1200, url: "/media/p1-1200w.webp" }] },
      { format: "jpg", widths: [{ width: 480, url: "/media/p1-480w.jpg" }, { width: 768, url: "/media/p1-768w.jpg" }, { width: 1200, url: "/media/p1.jpg" }] },
    ],
  },
  "/media/p2.jpg": {
    placeholder: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGgAAAgIDAAAAAAAAAAAAAAAAAAMFBgECBP/EACkQAAIBAgUCBQUAAAAAAAAAAAECAwARBBITITEFkTIzUWHBNEFxgeH/xAAWAQEBAQAAAAAAAAAAAAAAAAADAgH/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEC/9oADAMBAAIRAxEAPwB0MwhxTQxq7HxH39v7SOqrDp6kymSZxdbeFRfg+tZBiOInOqwYAqw4Hp81HzrnjsHuvOX7A0J1hk7xrtFyABtyO1FaupzGyt3oraawrgpnMj54sspuBvcb337Us9OxGobq5BbNmQD5qQwPlLXUeKMZcq7iOlgSAyOqMRexvf8AdFPx31J/FFWEbf/Z",
    sources: [
      { format: "avif", widths: [{ width: 480, url: "/media/p2-480w.avif" }, { width: 768, url: "/media/p2-768w.avif" }, { width: 1200, url: "/media/p2-1200w.avif" }] },
      { format: "webp", widths: [{ width: 480, url: "/media/p2-480w.webp" }, { width: 768, url: "/media/p2-768w.webp" }, { width: 1200, url: "/media/p2-1200w.webp" }] },
      { format: "jpg", widths: [{ width: 480, url: "/media/p2-480w.jpg" }, { width: 768, url: "/media/p2-768w.jpg" }, { width: 1200, url: "/media/p2.jpg" }] },
    ],
  },
  "/media/p3.jpg": {
    placeholder: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABQAEA//EACYQAAICAQMCBgMAAAAAAAAAAAECAAMRBCExIlEFBhIUMoEzYfH/xAAXAQADAQAAAAAAAAAAAAAAAAAAAgMB/8QAGREBAQADAQAAAAAAAAAAAAAAAAECERIh/9oADAMBAAIRAxEAPwBY1ois77KozMWmsst1RR9wwOB2xE9fUF0ZA5LACAl83KyOQwtVWH3KzIlhM1DPEppsTrMo3RdCdR48b0VUqNno32GBn+Qr3tiOWfTkZcPz2OZN+L6nSv4CQVaR5jcDqUMx3ORx+pTO3Mpnof/Z",
    sources: [
      { format: "avif", widths: [{ width: 480, url: "/media/p3-480w.avif" }, { width: 768, url: "/media/p3-768w.avif" }, { width: 1200, url: "/media/p3-1200w.avif" }] },
      { format: "webp", widths: [{ width: 480, url: "/media/p3-480w.webp" }, { width: 768, url: "/media/p3-768w.webp" }, { width: 1200, url: "/media/p3-1200w.webp" }] },
      { format: "jpg", widths: [{ width: 480, url: "/media/p3-480w.jpg" }, { width: 768, url: "/media/p3-768w.jpg" }, { width: 1200, url: "/media/p3.jpg" }] },
    ],
  },
  "/media/p4.jpg": {
    placeholder: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAIDBAUG/8QAJBAAAQMDAwQDAAAAAAAAAAAAAQACAwQREiExcSIzNWFDcsH/xAAWAQEBAQAAAAAAAAAAAAAAAAABAAL/xAAXEQEBAQEAAAAAAAAAAAAAAAAAEQES/9oADAMBAAIRAxEAPwDoZ2Nja5ztGjUlY1XWZENiu2zrH2tOsrIpaaUNOpBACwJHDM/Zv6s9GBjiciSSSdyhI1w15QqmIZJHwWu++QBa8bFV3TyZZEOI36DdPN4um4CrwfHyFjUU1TQTlJID6CFTn7zuUJgr/9k=",
    sources: [
      { format: "avif", widths: [{ width: 480, url: "/media/p4-480w.avif" }, { width: 768, url: "/media/p4-768w.avif" }, { width: 1200, url: "/media/p4-1200w.avif" }] },
      { format: "webp", widths: [{ width: 480, url: "/media/p4-480w.webp" }, { width: 768, url: "/media/p4-768w.webp" }, { width: 1200, url: "/media/p4-1200w.webp" }] },
      { format: "jpg", widths: [{ width: 480, url: "/media/p4-480w.jpg" }, { width: 768, url: "/media/p4-768w.jpg" }, { width: 1200, url: "/media/p4.jpg" }] },
    ],
  },
  "/media/p5.jpg": {
    placeholder: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAQBAgUD/8QAIhAAAgIBAwUBAQAAAAAAAAAAAQIAAxEEEjIhIjFBUQUT/8QAFgEBAQEAAAAAAAAAAAAAAAAAAgMB/8QAGREAAwEBAQAAAAAAAAAAAAAAAAECESID/9oADAMBAAIRAxEAPwBHUWJQdrKS2M9JmWaq644QCsHx9mr+kofVEADiBgD3mUARWP8AKvaPX2GvStwqoRlLS2O4En6RCP6l2awHAHaBCT6HyiiWMgOa2Zg0ZFhFeSuDt8mLafiZ3HCZS0yXgq129iSvWEh+RhKIJ//Z",
    sources: [
      { format: "avif", widths: [{ width: 480, url: "/media/p5-480w.avif" }, { width: 768, url: "/media/p5-768w.avif" }, { width: 1200, url: "/media/p5-1200w.avif" }] },
      { format: "webp", widths: [{ width: 480, url: "/media/p5-480w.webp" }, { width: 768, url: "/media/p5-768w.webp" }, { width: 1200, url: "/media/p5-1200w.webp" }] },
      { format: "jpg", widths: [{ width: 480, url: "/media/p5-480w.jpg" }, { width: 768, url: "/media/p5-768w.jpg" }, { width: 1200, url: "/media/p5.jpg" }] },
    ],
  },
  "/media/p6.jpg": {
    placeholder: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAQCBQYD/8QAKBAAAgEEAQIEBwAAAAAAAAAAAQIDAAQRIRIxcQUTIjQyQoGRobHR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAYEQEBAAMAAAAAAAAAAAAAAAAAARESUf/aAAwDAQACEQMRAD8AYtPHchV5yKyjADNyB706L+eWIEykqxwfLGT/AGs7bWi+Uszt8Wwq9aaV40UKttKeQGS7cAAe3WmxIaDSLnjfOoJzgvg/mioRJbpGAsUbDHU7J+9FNrwxOlkiulKFI3jjjHpA11G81yvWmlVRotkE5OwcarQx/L3qn8U9y30qWCvlt5w3pkca3yU5zRVrY+2Hc/uipgf/2Q==",
    sources: [
      { format: "avif", widths: [{ width: 480, url: "/media/p6-480w.avif" }, { width: 768, url: "/media/p6-768w.avif" }, { width: 1200, url: "/media/p6-1200w.avif" }] },
      { format: "webp", widths: [{ width: 480, url: "/media/p6-480w.webp" }, { width: 768, url: "/media/p6-768w.webp" }, { width: 1200, url: "/media/p6-1200w.webp" }] },
      { format: "jpg", widths: [{ width: 480, url: "/media/p6-480w.jpg" }, { width: 768, url: "/media/p6-768w.jpg" }, { width: 1200, url: "/media/p6.jpg" }] },
    ],
  },
};

export const MIME: Record<ImageFormat, string> = {
  avif: "image/avif",
  webp: "image/webp",
  jpg: "image/jpeg",
};
