/**
 * Regenerates src/lib/image-variants.ts from the CDN asset pointers in
 * src/assets/home (originals) and src/assets/home/variants (resized widths in
 * jpg / webp / avif), plus the blur-up placeholders in scripts/lqip.json.
 *
 * To add a new CMS image with responsive sizes:
 *   1. resize + re-encode locally, for each width in 480/768/1200(/1600/1920):
 *        magick in.jpg -resize 1200x -strip -quality 78 out/<name>-1200w.jpg
 *        magick in.jpg -resize 1200x -strip -quality 72 out/<name>-1200w.webp
 *        magick in.jpg -resize 1200x -strip -quality 50 out/<name>-1200w.avif
 *   2. upload each with:
 *        asset-cdn create --file out/<name>-1200w.avif --filename in-<name>-1200w.avif \
 *          > src/assets/home/variants/<name>-1200w.avif.asset.json
 *   3. add a 20px-wide base64 blur placeholder to scripts/lqip.json:
 *        magick in.jpg -resize 20x -strip -quality 40 lqip.jpg
 *   4. add the original's pixel width to ORIGINAL_WIDTHS below
 *   5. run: bun scripts/build-image-manifest.ts
 *
 * Only covers the images that ship with the build. Images uploaded through
 * the CMS generate their own widths at upload time and store the manifest in
 * homepage_content.image_variants, so this script does NOT need re-running
 * after a content edit — only when the bundled assets themselves change.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const HOME = "src/assets/home";
const VARIANTS = path.join(HOME, "variants");
const LQIP_FILE = "scripts/lqip.json";
const OUT = "src/lib/image-variants.ts";

/** Pixel width of each full-size original (add an entry when you add an image). */
const ORIGINAL_WIDTHS: Record<string, number> = {
  hero: 1920,
  p1: 1200,
  p2: 1200,
  p3: 1200,
  p4: 1200,
  p5: 1200,
  p6: 1200,
};

type Format = "avif" | "webp" | "jpg";
const FORMATS: Format[] = ["avif", "webp", "jpg"];

const readUrl = (file: string) => JSON.parse(readFileSync(file, "utf8")).url as string;

const lqip: Record<string, string> = existsSync(LQIP_FILE)
  ? JSON.parse(readFileSync(LQIP_FILE, "utf8"))
  : {};

const originals = readdirSync(HOME).filter((f) => f.endsWith(".asset.json"));
const variantFiles = readdirSync(VARIANTS).filter((f) => f.endsWith(".asset.json"));

interface Entry {
  placeholder?: string;
  sources: { format: Format; widths: { width: number; url: string }[] }[];
}

const entries: Record<string, Entry> = {};

for (const orig of originals) {
  const name = orig.replace(/\.jpg\.asset\.json$/, "");
  const url = readUrl(path.join(HOME, orig));
  const originalWidth = ORIGINAL_WIDTHS[name];

  const sources = FORMATS.map((format) => {
    const widths = variantFiles
      .filter((v) => v.startsWith(`${name}-`) && v.endsWith(`.${format}.asset.json`))
      .map((v) => ({
        width: Number(v.match(/-(\d+)w\./)?.[1] ?? 0),
        url: readUrl(path.join(VARIANTS, v)),
      }))
      .filter((v) => v.width > 0);
    // the untouched original is the widest jpg candidate
    if (format === "jpg" && originalWidth && !widths.some((w) => w.width === originalWidth)) {
      widths.push({ width: originalWidth, url });
    }
    return { format, widths: widths.sort((a, b) => a.width - b.width) };
  }).filter((s) => s.widths.length > 0);

  if (!sources.length) continue;
  entries[url] = { ...(lqip[name] ? { placeholder: lqip[name] } : {}), sources };
}

const serialize = (e: Entry) =>
  `{\n${e.placeholder ? `    placeholder: ${JSON.stringify(e.placeholder)},\n` : ""}    sources: [\n${e.sources
    .map(
      (s) =>
        `      { format: "${s.format}", widths: [${s.widths
          .map((w) => `{ width: ${w.width}, url: ${JSON.stringify(w.url)} }`)
          .join(", ")}] },`,
    )
    .join("\n")}\n    ],\n  }`;

const body = Object.entries(entries)
  .map(([url, e]) => `  ${JSON.stringify(url)}: ${serialize(e)},`)
  .join("\n");

writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/build-image-manifest.ts — do not edit by hand.
// Maps each CMS homepage image URL to its responsive widths per format
// (AVIF first, then WebP, then the JPEG fallback every browser understands)
// plus a tiny base64 blur-up placeholder.
export type ImageFormat = "avif" | "webp" | "jpg";
export interface ImageWidth { width: number; url: string }
export interface ImageSource { format: ImageFormat; widths: ImageWidth[] }
export interface ImageEntry { placeholder?: string; sources: ImageSource[] }

export const IMAGE_VARIANTS: Record<string, ImageEntry> = {
${body}
};

export const MIME: Record<ImageFormat, string> = {
  avif: "image/avif",
  webp: "image/webp",
  jpg: "image/jpeg",
};
`,
);

console.log(`wrote ${OUT} (${Object.keys(entries).length} images)`);
